server:
  port: 8190
  servlet:
    context-path: /dao
    session:
      timeout: 60s
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
